name: Update Image List

permissions: write-all

on:
  push:
    paths:
      - "**.png"
      - "docs/README*"
      - "docs/scripts/**"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: pdm-project/setup-pdm@v3

      - name: Run Job
        run: |-
          # pdm install  # no 3rd lib used
          pdm run generate

          pnpm i
          pnpm format

          if [[ -n "$(git status -s)" ]]; then
            git add .
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -m "Update Image List"
            git push
          else
            echo "No changes detected."
          fi
